### ISSUE TITLE
Support Silent install (Windows Package Manager submission req.)

### ISSUE THREAD

**Issue by cub525** [openstenoproject/plover#1354]
**Describe the solution you'd like**

Follow the directions from [here](https://docs.microsoft.com/en-us/windows/package-manager/package/repository)

**Additional context**

I might start contributing to this repo as soon as I figure out the structure, I think it's a really cool project.

**Comment by cub525** [comment]
Here is a set of Manifests, created with the windows package manifest creator (wingetcreate).
Version manifest preview:  


```YAML
# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: OpenStenoProject.Plover
PackageVersion: 4.0.0.10
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
```
Installer manifest preview:
```YAML
# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: OpenStenoProject.Plover
PackageVersion: 4.0.0.10
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/openstenoproject/plover/releases/download/continuous/plover-4.0.0.dev10+2.g0501aa3-win64.setup.exe
  InstallerSha256: 0A3E0FA31D0A7C6C5432244F4123EB243AE1749721BC7DF1538444EF6ABC8845
ManifestType: installer
ManifestVersion: 1.0.0
```

Default locale manifest preview:
```YAML
# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: OpenStenoProject.Plover
PackageVersion: 4.0.0.10
PackageLocale: en-US
Publisher: Open Steno Project
PackageName: Plover
License: GPL 2.0
ShortDescription: Plover (rhymes with "lover") is a desktop application that allows anyone to use stenography to write on their computer, up to speeds of 200WPM and beyond.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
```
