### ISSUE TITLE
Plover only handling 6 keys for NKRO keyboard

### ISSUE THREAD

**Issue by GuiltyDolphin** [openstenoproject/plover#644]
Classification: Bug

Reproducibility: Always

## Summary

I'm using a [VicTop mechanical keyboard with NKRO](https://www.amazon.co.uk/gp/product/B01DBYNVSY) on Linux Mint (17). The NKRO features works fine on pretty much everything except Plover. Plover will only register 6 keys at a time which makes it a pain to type!

## Steps to Reproduce

1. Buy [this keyboard](https://www.amazon.co.uk/gp/product/B01DBYNVSY).
2. Run Plover
3. Try and type with more than 6 keys at once.

## Expected Results

3. More than 6 keys register.

## Actual Results

3. Only 6 keys register.

## Version

Plover version 3.1.0

Installed via: GitHub

## Configuration

OS: Linux Mint 17 (Cinnamon)

**Comment by morinted** [comment]
Can you test on Windows as well?

**Comment by morinted** [comment]
I'd also appreciate if you could confirm that NKRO works on something like the browser test page here: http://www.gigahype.com/nkey-rollover-test-page/

**Comment by GuiltyDolphin** [comment]
@morinted Unfortunately I cannot test on Windows as I do not have access to a Windows machine.

From testing on that site (and others including software) the NKRO works fine. I only experience the issue in Plover.

**Comment by morinted** [comment]
This is a long shot, for sure, but there have been many changes in how we handle the keyboard in Linux in the past year. Would you be able to try 2.5.8 and see if the issue existed back then, too? 

Thanks for the feedback that the website works.

**Comment by GuiltyDolphin** [comment]
@morinted Okay, it appears to work with version 2.5.8.

Also, I was having a look around and found this reference to a similar issue in the past: https://github.com/openstenoproject/plover/pull/60#issuecomment-64174417

**Comment by GuiltyDolphin** [comment]
@morinted I've done a bit more digging and it looks like 840d1a4600 breaks it (build on previous commit works fine, build on that commit doesn't work with NKRO).

**Comment by GuiltyDolphin** [comment]
@morinted I've narrowed it down a bit more and it looks like in `run`, the display is only passing 6 keypress events (via `next_event`).

**Comment by GuiltyDolphin** [comment]
@benoit-pierre It appears to only recognize the first 6 keys:

```
USB Keyboard                            	id=14	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 14. Type: XIKeyClass
		Keycodes supported: 248

EVENT type 13 (RawKeyPress)
    device: 14 (14)
    detail: 47
    valuators:

EVENT type 13 (RawKeyPress)
    device: 14 (14)
    detail: 38
    valuators:

EVENT type 13 (RawKeyPress)
    device: 14 (14)
    detail: 39
    valuators:

EVENT type 13 (RawKeyPress)
    device: 14 (14)
    detail: 40
    valuators:

EVENT type 13 (RawKeyPress)
    device: 14 (14)
    detail: 41
    valuators:

EVENT type 13 (RawKeyPress)
    device: 14 (14)
    detail: 44
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 14 (14)
    detail: 47
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 14 (14)
    detail: 38
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 14 (14)
    detail: 39
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 14 (14)
    detail: 40
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 14 (14)
    detail: 41
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 14 (14)
    detail: 44
    valuators:
```

I've also tried `xev` which seems to work fine.

**Comment by benoit-pierre** [comment]
Can you upload the full output? Also what does `xinput list` report?

**Comment by GuiltyDolphin** [comment]
@benoit-pierre That is the full output from `xinput` (bar the key press and release for `^C` to exit). If I press the home row keys (SKWR RBGS) then Plover will fairly consistently show the SKWR RS keys being pressed.

Output from `xinput list` (ID has changed as it has since been replugged):

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=12	[slave  pointer  (2)]
⎜   ↳ USB Keyboard                            	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ HD WebCam                               	id=10	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=11	[slave  keyboard (3)]
    ↳ Acer WMI hotkeys                        	id=13	[slave  keyboard (3)]
    ↳ USB Keyboard                            	id=15	[slave  keyboard (3)]
```

**Comment by benoit-pierre** [comment]
What I was trying to determine is if the keyboard driver does some ugly things like creating new devices dynamically to work around the core HID limitations of 6 keys + modifiers. Anyway, I've checked the source code for `xinput test-xi2`, and the monitoring is done on all devices (and so work if a new keyboard is plugged), so I guess it's a bug in Xinput? You'll have to open a bug there: https://bugs.freedesktop.org/

**Comment by GuiltyDolphin** [comment]
@benoit-pierre Okay, thanks for looking into this. I've opened a bug over on the bug tracker: https://bugs.freedesktop.org/show_bug.cgi?id=98762

**Comment by GuiltyDolphin** [comment]
@benoit-pierre Thanks to Peter Hutterer's help it looks like this isn't an issue with xinput, and he did have the following comment:

> The second cause would be that plover is doing something incorrect with the keyboard events. Whenever the other event node gets active an XIDeviceChangedEvent is sent to notify the client. It may be that this is confusing plover? Or plover is listening to the slave devices directly? I don't know.

_Are_ we listening to the slave devices directly? _Are_ we handling the XIDeviceChangedEvent events?

**Comment by benoit-pierre** [comment]
I'm confused, reading the comments on the Freedesktop bug report, it looks like `xinput test-xi2` does actually work? And I mean this exact command, not without specifying a device number; can you confirm? Because when not specifying said device number, the code will use the special `AllDevices` or `AllMasterDevices` parameter to listen to all devices, which will also automatically pick up new devices (if you plug a new keyboard while the command is running, or if you're keyboard does funny things to implement NKRO). Plover itself does not use `AllDevices/AllMasterDevices` because it needs to ignore the fake XTEST keyboard, and does not listen to other Xinput events (like XIDeviceChangedEvent, or XIHierarchyChangedEvent). So it does not work if you dynamically plug a new keyboard while Plover is running, that's a known issue.

**Comment by GuiltyDolphin** [comment]
@benoit-pierre The keyboard exposes two devices, but I was only listening to one before.

The output works with no devices specified, and if devices `11` and `12` (from the list below) are specified in separate instances then all the keys can be accounted for (though only through `RawKeyPress`es and `RawKeyRelease`s).

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=15	[slave  pointer  (2)]
⎜   ↳ USB Keyboard                            	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ HD WebCam                               	id=10	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=14	[slave  keyboard (3)]
    ↳ Acer WMI hotkeys                        	id=16	[slave  keyboard (3)]
    ↳ USB Keyboard                            	id=12	[slave  keyboard (3)]
```

Could we not just explicitly ignore events from the XTEST keyboard?

**Comment by benoit-pierre** [comment]
> Could we not just explicitly ignore events from the XTEST keyboard?

No, it's not that simple, we also need to suppress the right devices.

Anyway, if device 11 sends keyboard events too, then it is a bug in Xinput! No? It's a pointer device! Does it change class dynamically? Is that what happen? Please give me the full output of running `xinput test-xi2` and pressing 6+ keys.

**Comment by GuiltyDolphin** [comment]
Output from `xinput list`:

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=15	[slave  pointer  (2)]
⎜   ↳ USB Keyboard                            	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ HD WebCam                               	id=10	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=14	[slave  keyboard (3)]
    ↳ Acer WMI hotkeys                        	id=16	[slave  keyboard (3)]
    ↳ USB Keyboard                            	id=11	[slave  keyboard (3)]
```

Output from `xinput test-xi2 --root`:

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=15	[slave  pointer  (2)]
⎜   ↳ USB Keyboard                            	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ HD WebCam                               	id=10	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=14	[slave  keyboard (3)]
    ↳ Acer WMI hotkeys                        	id=16	[slave  keyboard (3)]
    ↳ USB Keyboard                            	id=11	[slave  keyboard (3)]
EVENT type 13 (RawKeyPress)
    device: 2 (12)
    detail: 45
    valuators:

EVENT type 2 (KeyPress)
    device: 12 (12)
    detail: 45
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 13 (RawKeyPress)
    device: 2 (12)
    detail: 46
    valuators:

EVENT type 2 (KeyPress)
    device: 12 (12)
    detail: 46
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 1 (DeviceChanged)
    device: 3 (11)
    reason: SlaveSwitch
	Reporting 1 classes:
		Class originated from: 11. Type: XIKeyClass
		Keycodes supported: 248

EVENT type 13 (RawKeyPress)
    device: 3 (11)
    detail: 47
    valuators:

EVENT type 2 (KeyPress)
    device: 11 (11)
    detail: 47
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 13 (RawKeyPress)
    device: 3 (11)
    detail: 38
    valuators:

EVENT type 2 (KeyPress)
    device: 11 (11)
    detail: 38
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 13 (RawKeyPress)
    device: 3 (11)
    detail: 39
    valuators:

EVENT type 2 (KeyPress)
    device: 11 (11)
    detail: 39
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 13 (RawKeyPress)
    device: 3 (11)
    detail: 40
    valuators:

EVENT type 2 (KeyPress)
    device: 11 (11)
    detail: 40
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 13 (RawKeyPress)
    device: 3 (11)
    detail: 41
    valuators:

EVENT type 2 (KeyPress)
    device: 11 (11)
    detail: 41
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 13 (RawKeyPress)
    device: 3 (11)
    detail: 44
    valuators:

EVENT type 2 (KeyPress)
    device: 11 (11)
    detail: 44
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 14 (RawKeyRelease)
    device: 2 (12)
    detail: 45
    valuators:

EVENT type 3 (KeyRelease)
    device: 12 (12)
    detail: 45
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 14 (RawKeyRelease)
    device: 2 (12)
    detail: 46
    valuators:

EVENT type 3 (KeyRelease)
    device: 12 (12)
    detail: 46
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 1 (DeviceChanged)
    device: 3 (11)
    reason: SlaveSwitch
	Reporting 1 classes:
		Class originated from: 11. Type: XIKeyClass
		Keycodes supported: 248

EVENT type 14 (RawKeyRelease)
    device: 3 (11)
    detail: 47
    valuators:

EVENT type 3 (KeyRelease)
    device: 11 (11)
    detail: 47
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 14 (RawKeyRelease)
    device: 3 (11)
    detail: 38
    valuators:

EVENT type 3 (KeyRelease)
    device: 11 (11)
    detail: 38
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 14 (RawKeyRelease)
    device: 3 (11)
    detail: 39
    valuators:

EVENT type 3 (KeyRelease)
    device: 11 (11)
    detail: 39
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 14 (RawKeyRelease)
    device: 3 (11)
    detail: 40
    valuators:

EVENT type 3 (KeyRelease)
    device: 11 (11)
    detail: 40
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 14 (RawKeyRelease)
    device: 3 (11)
    detail: 41
    valuators:

EVENT type 3 (KeyRelease)
    device: 11 (11)
    detail: 41
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
EVENT type 14 (RawKeyRelease)
    device: 3 (11)
    detail: 44
    valuators:

EVENT type 3 (KeyRelease)
    device: 11 (11)
    detail: 44
    flags:
    root: 432.46/308.09
    event: 432.46/308.09
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x9d event 0x9d child 0x160245b
```

Output from `xinput test-xi2 --root 11`:

```
USB Keyboard                            	id=11	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 11. Type: XIKeyClass
		Keycodes supported: 248

EVENT type 13 (RawKeyPress)
    device: 11 (11)
    detail: 47
    valuators:

EVENT type 13 (RawKeyPress)
    device: 11 (11)
    detail: 38
    valuators:

EVENT type 13 (RawKeyPress)
    device: 11 (11)
    detail: 39
    valuators:

EVENT type 13 (RawKeyPress)
    device: 11 (11)
    detail: 40
    valuators:

EVENT type 13 (RawKeyPress)
    device: 11 (11)
    detail: 41
    valuators:

EVENT type 13 (RawKeyPress)
    device: 11 (11)
    detail: 44
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 11 (11)
    detail: 47
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 11 (11)
    detail: 38
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 11 (11)
    detail: 39
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 11 (11)
    detail: 40
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 11 (11)
    detail: 41
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 11 (11)
    detail: 44
    valuators:
```

Output from `xinput test-xi2 --root 12`:

```
USB Keyboard                            	id=12	[slave  pointer  (2)]
	Reporting 6 classes:
		Class originated from: 12. Type: XIButtonClass
		Buttons supported: 7
		Button labels: "Button 0" "Button Unknown" "Button Unknown" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right"
		Button state:
		Class originated from: 12. Type: XIKeyClass
		Keycodes supported: 248
		Class originated from: 12. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: -1.000000 - -1.000000
		  Resolution: 1 units/m
		  Mode: relative
		Class originated from: 12. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: -1.000000 - -1.000000
		  Resolution: 1 units/m
		  Mode: relative
		Class originated from: 12. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Wheel
		  Range: -1.000000 - -1.000000
		  Resolution: 1 units/m
		  Mode: relative
		Class originated from: 12. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 1.000000
		  flags: 0x0

EVENT type 13 (RawKeyPress)
    device: 12 (12)
    detail: 46
    valuators:

EVENT type 13 (RawKeyPress)
    device: 12 (12)
    detail: 45
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 12 (12)
    detail: 45
    valuators:

EVENT type 14 (RawKeyRelease)
    device: 12 (12)
    detail: 46
    valuators:
```
